name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

env:
  PROJECT_PATH: 'ForTest.sln'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
          
    - name: Restore packages
      run: dotnet restore ${{ env.PROJECT_PATH }}
      
    - name: Build project
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
